name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /www/wwwroot/medipos-client

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm install

            echo "Building..."
            npm run build